title: Zacharie Esperanza
logo: "/images/TDOV.PNG?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Just an Animator who tried out Programming
  <br><br>
  No really, I tried lol
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
